version: "3.7"

services:
  api:
    container_name: wb-l0_api
    build:
      context: ..
      dockerfile: build/Dockerfile
      args:
        LDFLAGS: ${LDFLAGS}
        WAIT_VERSION: ${WAIT_VERSION:-2.9.0}
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}