version: "3.7"

services:
  api:
    container_name: wb-l0_api
    build:
      context: ..
      dockerfile: build/Dockerfile
      args:
        LDFLAGS: ${LDFLAGS}
        WAIT_VERSION: ${WAIT_VERSION:-2.9.0}
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - migrator

  migrator:
    container_name: wb-l0_migrator
    build:
      context: ..
      dockerfile: build/migrator/Dockerfile
      args:
        WAIT_VERSION: ${WAIT_VERSION:-2.9.0}
        GOOSE_VERSION: ${GOOSE_VERSION:-3.6.0}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DBNAME
      - POSTGRES_SSLMODE
    restart: on-failure
    volumes:
      - ../migrations:/migrations
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    container_name: wb-l0_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: